spring:
  datasource:
    url: jdbc:mysql://kk-dev-db.crzwvwz08nz1.ap-southeast-1.rds.amazonaws.com:3306/evoucher?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true&useLegacyDatetimeCode=false
    username: kk_dev_db
    password: AwUW&3TFDJ7T^zcn

  #db configuration
  #spring.
  jpa:
    #spring.jpa.
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: false
      jdbc:
        batch_size: 500
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    #spring.jpa.
    hibernate:
      naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MySQL5Dialect
      #ddl-auto: create-drop
      ddl-auto: create

    #spring.jpa
    generate-ddl: false
    open-in-view: false
    show-sql: true

  #spring.mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: tule.java@gmail.com
    password: 9781695123aB!
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true


  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

    security:
      oauth2:
        client:
          registration:
            facebook:
              clientId: 2122962537991193
              clientSecret: b266119b238d7a7941793a057872baea
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - public_profile
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

# tomcat server config
server:
  port:
    9129
  ssl:
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: canu
  tomcat:
    max-threads: 10
    min-spare-threads: 5
